module.exports = {
	CARD_SENT:"CARD_SENT",
	CARD_RECIEVED: "CARD_RECIEVED",
	VERIFY_USER: 'VERIFY_USER',
	USER_CONNECTED:"USER_CONNECTED",
	USER_DISCONNECTED:"USER_DISCONNECTED",
	LOGOUT:"LOGOUT",
	MY_STATE:"MY_STATE"


}